### ISSUE TITLE
It seems that the dvs_tracking cannot work?

### ISSUE THREAD

**Issue by KwanWaiPang** [uzh-rpg/rpg_dvs_evo_open#11]
no matter which launch file, after running, it will appear error:
================================================================================REQUIRED process [dvs_tracking-7] has died!
process has died [pid 4972, exit code -11, cmd /home/kwanwaipang/catkin_ws_dvs/devel/lib/dvs_tracking/dvs_tracking_ros events:=/dvs/events remote_key:=/evo/remote_key pointcloud:=dvs_mapping/pointcloud __name:=dvs_tracking __log:=/home/kwanwaipang/.ros/log/b690b020-19d6-11ec-bb55-4074e020cd12/dvs_tracking-7.log].
log file: /home/kwanwaipang/.ros/log/b690b020-19d6-11ec-bb55-4074e020cd12/dvs_tracking-7*.log
Initiating shutdown!
================================================================================

**Comment by KwanWaiPang** [comment]
> Hello, I have the same problem. Have you solved it now?
> # ================================================================================REQUIRED process [dvs_tracking-7] has died!
> process has died [pid 22729, exit code -11, cmd /home/scx/catkin_ws_dvs/devel/lib/dvs_tracking/dvs_tracking_ros events:=/dvs/events remote_key:=/evo/remote_key pointcloud:=dvs_mapping/pointcloud __name:=dvs_tracking __log:=/home/scx/.ros/log/28fb0ecc-3317-11ec-879c-08002733e6bf/dvs_tracking-7.log].
> log file: /home/scx/.ros/log/28fb0ecc-3317-11ec-879c-08002733e6bf/dvs_tracking-7*.log
> Initiating shutdown!
> 
> [ INFO] [1634893512.158066902]: Found parameter: min_depth, value: 0.4 [ INFO] [1634893512.162070559]: Found parameter: max_depth, value: 5 [ INFO] [1634893512.162827472]: Found parameter: num_depth_cells, value: 100 [ INFO] [1634893512.163540563]: Found parameter: adaptive_threshold_kernel_size, value: 5 [ INFO] [1634893512.164218385]: Found parameter: adaptive_threshold_c, value: 10 [ INFO] [1634893512.171110850]: Found parameter: auto_trigger, value: 1 [rviz-13] killing on exit [dvs_renderer_left-12] killing on exit [rqt_evo-11] killing on exit [snakify-10] killing on exit [tf_to_camera_marker-9] killing on exit [dvs_bootstrapping-8] killing on exit Traceback (most recent call last): File "/home/scx/catkin_ws_dvs/src/rpg_dvs_evo_open/evo_utils/src/evo_utils/tf_to_camera_markers.py", line 9, in from tf import TransformListener File "/opt/ros/melodic/lib/python2.7/dist-packages/tf/**init**.py", line 30, in from tf2_ros import TransformException as Exception, ConnectivityException, LookupException, ExtrapolationException File "/opt/ros/melodic/lib/python2.7/dist-packages/tf2_ros/**init**.py", line 39, in from .buffer_interface import * File "/opt/ros/melodic/lib/python2.7/dist-packages/tf2_ros/buffer_interface.py", line 32, in import roslib; roslib.load_manifest('tf2_ros') File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 64, in load_manifest sys.path = _generate_python_path(package_name, _rospack) + sys.path File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 97, in _generate_python_path m = rospack.get_manifest(pkg) File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 171, in get_manifest return self._load_manifest(name) File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 215, in _load_manifest retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name, rospack=self) File "/usr/lib/python2.7/dist-packages/rospkg/manifest.py", line 410, in parse_manifest_file from rosdep2.rospack import init_rospack_interface, is_ros_package, is_system_dependency, is_view_empty File "/usr/lib/python2.7/dist-packages/rosdep2/**init**.py", line 45, in from .lookup import RosdepDefinition, RosdepView, RosdepLookup, File "/usr/lib/python2.7/dist-packages/rosdep2/lookup.py", line 44, in from .sources_list import SourcesListLoader File "/usr/lib/python2.7/dist-packages/rosdep2/sources_list.py", line 30, in from **future** import print_function KeyboardInterrupt [dvs_tracking-7] killing on exit [trigger_map_expansion-6] killing on exit Traceback (most recent call last): File "/home/scx/catkin_ws_dvs/src/rpg_dvs_evo_open/dvs_mapping/src/trigger_map_expansion.py", line 11, in from tf import TransformListener File "/opt/ros/melodic/lib/python2.7/dist-packages/tf/**init**.py", line 30, in from tf2_ros import TransformException as Exception, ConnectivityException, LookupException, ExtrapolationException File "/opt/ros/melodic/lib/python2.7/dist-packages/tf2_ros/**init**.py", line 39, in from .buffer_interface import * File "/opt/ros/melodic/lib/python2.7/dist-packages/tf2_ros/buffer_interface.py", line 32, in import roslib; roslib.load_manifest('tf2_ros') File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 64, in load_manifest sys.path = _generate_python_path(package_name, _rospack) + sys.path File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 97, in _generate_python_path m = rospack.get_manifest(pkg) File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 171, in get_manifest return self._load_manifest(name) File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 215, in _load_manifest retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name, rospack=self) File "/usr/lib/python2.7/dist-packages/rospkg/manifest.py", line 410, in parse_manifest_file [dvs_mapping-5] killing on exit from rosdep2.rospack import init_rospack_interface, is_ros_package, is_system_dependency, is_view_empty File "/usr/lib/python2.7/dist-packages/rosdep2/**init**.py", line 45, in from .lookup import RosdepDefinition, RosdepView, RosdepLookup, File "/usr/lib/python2.7/dist-packages/rosdep2/lookup.py", line 44, in from .sources_list import SourcesListLoader File "/usr/lib/python2.7/dist-packages/rosdep2/sources_list.py", line 50, in from .gbpdistro_support import get_gbprepo_as_rosdep_data, download_gbpdistro_as_rosdep_data File "/usr/lib/python2.7/dist-packages/rosdep2/gbpdistro_support.py", line 18, in from .platforms.debian import APT_INSTALLER File "/usr/lib/python2.7/dist-packages/rosdep2/platforms/debian.py", line 45, in from .pip import PIP_INSTALLER File "/usr/lib/python2.7/dist-packages/rosdep2/platforms/pip.py", line 33, in import pkg_resources File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 403, in darwinVersionString = re.compile(r"darwin-(\d+).(\d+).(\d+)-(.*)") File "/usr/lib/python2.7/re.py", line 194, in compile return _compile(pattern, flags) File "/usr/lib/python2.7/re.py", line 249, in _compile p = sre_compile.compile(pattern, flags) File "/usr/lib/python2.7/sre_compile.py", line 576, in compile code = _code(p, flags) File "/usr/lib/python2.7/sre_compile.py", line 561, in _code _compile(code, p.data, flags) File "/usr/lib/python2.7/sre_compile.py", line 151, in _compile _compile(code, av[1], flags) File "/usr/lib/python2.7/sre_compile.py", line 124, in _compile elif _simple(av) and op is not REPEAT: File "/usr/lib/python2.7/sre_compile.py", line 431, in _simple return lo == hi == 1 and av[2][0][0] != SUBPATTERN File "/usr/lib/python2.7/sre_parse.py", line 143, in **getitem** if isinstance(index, slice): KeyboardInterrupt [pose_to_tf-4] killing on exit [svo_gui-3] killing on exit Traceback (most recent call last): File "/home/scx/catkin_ws_dvs/src/rpg_dvs_evo_open/dvs_bootstrapping/src/pose_to_tf.py", line 4, in import tf File "/opt/ros/melodic/lib/python2.7/dist-packages/tf/**init**.py", line 30, in from tf2_ros import TransformException as Exception, ConnectivityException, LookupException, ExtrapolationException File "/opt/ros/melodic/lib/python2.7/dist-packages/tf2_ros/**init**.py", line 39, in from .buffer_interface import * File "/opt/ros/melodic/lib/python2.7/dist-packages/tf2_ros/buffer_interface.py", line 32, in import roslib; roslib.load_manifest('tf2_ros') File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 64, in load_manifest sys.path = _generate_python_path(package_name, _rospack) + sys.path File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 97, in _generate_python_path m = rospack.get_manifest(pkg) File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 171, in get_manifest return self._load_manifest(name) File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 215, in _load_manifest retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name, rospack=self) File "/usr/lib/python2.7/dist-packages/rospkg/manifest.py", line 414, in parse_manifest_file _static_rosdep_view = init_rospack_interface() File "/usr/lib/python2.7/dist-packages/rosdep2/rospack.py", line 61, in init_rospack_interface return lookup.get_rosdep_view(DEFAULT_VIEW_KEY) File "/usr/lib/python2.7/dist-packages/rosdep2/lookup.py", line 625, in get_rosdep_view view = self.create_rosdep_view(view_key, dependencies + [view_key], verbose=verbose) File "/usr/lib/python2.7/dist-packages/rosdep2/lookup.py", line 570, in create_rosdep_view view.merge(db_entry, verbose=verbose) File "/usr/lib/python2.7/dist-packages/rosdep2/lookup.py", line 222, in merge for dep_name, dep_data in update_entry.rosdep_data.items(): KeyboardInterrupt Traceback (most recent call last): File "/opt/ros/melodic/lib/rqt_gui/rqt_gui", line 13, in sys.exit(main.main()) File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_gui/main.py", line 65, in main hash(os.environ['ROS_PACKAGE_PATH']))) File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_gui/main.py", line 444, in main app = self.create_application(argv) File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_gui/main.py", line 69, in create_application app = super(Main, self).create_application(argv) File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_gui/main.py", line 210, in create_application app = QApplication(argv) KeyboardInterrupt Traceback (most recent call last): File "/home/scx/catkin_ws_dvs/src/rpg_dvs_evo_open/rqt_evo/scripts/rqt_evo", line 10, in sys.exit(main.main(sys.argv, standalone=plugin)) # , plugin_argument_provider=Evo.add_arguments File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_gui/main.py", line 65, in main hash(os.environ['ROS_PACKAGE_PATH']))) File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_gui/main.py", line 444, in main app = self.create_application(argv) File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_gui/main.py", line 69, in create_application app = super(Main, self).create_application(argv) File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_gui/main.py", line 210, in create_application app = QApplication(argv) KeyboardInterrupt [svo-2] killing on exit [pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud! [rosout-1] killing on exit [master] killing on exit shutting down processing monitor... ... shutting down processing monitor complete done

I think this program can not work at all.

**Comment by zebrajiahao** [comment]
@lienharj  @KwanWaiPang  I could run it when opencv downgraded to 3.2.0
![943e564d0a8d412f84c38464e69b539b](https://user-images.githubusercontent.com/37396275/139635702-be377bdc-d08e-4c6a-8539-a2f7bd65b9e1.png)

**Comment by xixixixiangxianguestc** [comment]
@zebrajiahao 
Hello, I used the version of opencv3.2.0, and the above problem still exists.
pkg-config --modversion opencv
3.2.0
I found that there is such an error, [pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud!
Are there any requirements for the version of pcl?

**Comment by zebrajiahao** [comment]
> @zebrajiahao Hello, I used the version of opencv3.2.0, and the above problem still exists. pkg-config --modversion opencv 3.2.0 I found that there is such an error, [pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud! Are there any requirements for the version of pcl?



It looks like no data has been read

**Comment by xixixixiangxianguestc** [comment]
Yes, you can add my WeChat through:  scxspingit，Thanks~

**Comment by youngOS1998** [comment]
@xixixixiangxianguestc hello, i have the same issue.  Have you solved it?

**Comment by SeaEastXu** [comment]
> 
I also have the same error. @xixixixiangxianguestc @youngOS1998
