### ISSUE TITLE
Bootstrapper looks well until the pipeline trigger the map expension！ publisherUpdate: unknown method name

### ISSUE THREAD

**Issue by xji-apex** [uzh-rpg/rpg_dvs_evo_open#14]
Hello！ Ask for help！！！
It looks well until the Pipeline triggers the map expension！(Initiating shutdown!)

I follow the  tutorial and launch the pipeline (for the SVO based bootstrapper):
`roslaunch dvs_tracking live.launch bootstrap_image_topic:=/dvs/image_raw auto_trigger:=false camera_name:=my_camera`
Then, I press the Start/Reset button in rqt_evo and press Update to create a map.  The map looks correct, so I press `Switch to tracking` to start tracking with EVO.
The EVO  pipeline tracks well under the created map, but if I move out of it, the pipeline is crushed! (my OpenCV version:3.2; DAVIS 346 camera is calibrated! )

The terminal shows as follows:
[INFO] [1635820905.897833]: Received map: 936 points
I20211102 10:41:46.827975 31398 depth_defocus_node.cpp:205] Received command: update
I20211102 10:41:46.831833 31398 depth_defocus_node.cpp:441] Received a map creation request
I20211102 10:41:46.831851 31398 depth_defocus_node.cpp:442] Setting KF at time: 1635820906.783920237
[ INFO] [1635820907.019704415]: Found parameter: type_focus_measure, value: 0
I20211102 10:41:47.049850 31415 tracker.cpp:233] Received new map: 1858 points
[INFO] [1635820907.051294]: Received map: 1858 points
I20211102 10:41:49.894567 31398 depth_defocus_node.cpp:205] Received command: switch
[ INFO] [1635820909.895934206]: Found parameter: dvs_bootstrap_frame_id, value: /camera_0
[ INFO] [1635820909.897304341]: Found parameter: min_map_size, value: 0
[ INFO] [1635820909.898593305]: Found parameter: min_n_keypoints, value: 0
**OpenCV Error:** Iterations do not converge (The algorithm stopped before its convergence. The correlation is going to be minimized. Images may be uncorrelated or non-overlapped) in findTransformECC, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/video/src/ecc.cpp, line 530
W20211102 10:41:56.931288 32562 motion_correction.cpp:69] The algorithm stopped before its convergence. The correlation is going to be minimized. Images may be uncorrelated or non-overlapped
OpenCV Error: Iterations do not converge (The algorithm stopped before its convergence. The correlation is going to be minimized. Images may be uncorrelated or non-overlapped) in findTransformECC, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/video/src/ecc.cpp, line 530
W20211102 10:41:59.631243 32562 motion_correction.cpp:69] The algorithm stopped before its convergence. The correlation is going to be minimized. Images may be uncorrelated or non-overlapped
*** Aborted at 1635820961 (unix time) try "date -d @1635820961" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGFPE (@0x7efe87367db8) received by PID 31415 (TID 0x7efe4a54d700) from PID 18446744071683079608; stack trace: ***
    @     0x7efe869f0040 (unknown)
    @     0x7efe87367db8 LKSE3::trackFrame()
    @     0x7efe87371d1a Tracker::estimateTrajectory()
    @     0x7efe8737249c Tracker::trackingThread()
    @     0x7efe870776df (unknown)
    @     0x7efe85e606db start_thread
    @     0x7efe86ad271f clone
    @                0x0 (unknown)
================================================================================REQUIRED process [dvs_tracking-6] has died!
process has died [pid 31415, exit code -8, cmd /home/wuji/ros_ws/evo_ws/devel/lib/dvs_tracking/dvs_tracking_ros events:=/dvs/events remote_key:=/evo/remote_key pointcloud:=dvs_mapping/pointcloud __name:=dvs_tracking __log:=/home/wuji/.ros/log/1ae98a4e-3b86-11ec-9dc3-200db04a1a6c/dvs_tracking-6.log].
log file: /home/wuji/.ros/log/1ae98a4e-3b86-11ec-9dc3-200db04a1a6c/dvs_tracking-6*.log
Initiating shutdown!
================================================================================
[rviz-13] killing on exit
[dvs_renderer_left-12] killing on exit
[rqt_evo-11] killing on exit
[snakify-10] killing on exit
[dvs_reconstruction-8] killing on exit
[tf_to_camera_marker-9] killing on exit
[dvs_tracking-6] killing on exit
[dvs_bootstrapping-7] killing on exit
[dvs_mapping-4] killing on exit
[pose_to_tf-3] killing on exit
[trigger_map_expansion-5] killing on exit
[svo_gui-2] killing on exit
[svo-1] killing on exit
OpenCV Error: Assertion failed (tlsSlots.size() > slotIdx) in releaseSlot, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/core/src/system.cpp, line 1092
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/core/src/system.cpp:1092: error: (-215) tlsSlots.size() > slotIdx in function releaseSlot

shutting down processing monitor...
... shutting down processing monitor complete
done

I open **the logs** and find the error:
[rosmaster.master][INFO] 2021-11-02 10:40:31,128: publisherUpdate[/evo/remote_key] -> http://localhost:29355/ ['http://localhost:19073/', 'http://localhost:14557/']: sec=0.00, result=[1, '', 0]
[rosmaster.master][INFO] 2021-11-02 10:40:31,128: publisherUpdate[/evo/remote_key] -> http://localhost:15449/ ['http://localhost:19073/', 'http://localhost:14557/']
[rosmaster.master][INFO] 2021-11-02 10:40:31,128: publisherUpdate[/evo/remote_key] -> http://localhost:15449/ ['http://localhost:19073/', 'http://localhost:14557/']: sec=0.00, result=[0, 'Unknown Error', 0]
[rosmaster.master][INFO] 2021-11-02 10:40:31,129: publisherUpdate[/rosout] -> http://localhost:9739/ ['http://localhost:10809/', 'http://localhost:24283/', 'http://localhost:19073/', 'http://localhost:15449/', 'http://localhost:29355/', 'http://localhost:4319/', 'http://localhost:18453/', 'http://localhost:26671/', 'http://localhost:9389/', 'http://localhost:23059/', 'http://localhost:14557/']
[rosmaster.master][INFO] 2021-11-02 10:40:31,129: publisherUpdate[/rosout] -> http://localhost:9739/ ['http://localhost:10809/', 'http://localhost:24283/', 'http://localhost:19073/', 'http://localhost:15449/', 'http://localhost:29355/', 'http://localhost:4319/', 'http://localhost:18453/', 'http://localhost:26671/', 'http://localhost:9389/', 'http://localhost:23059/', 'http://localhost:14557/']: sec=0.00, result=[1, '', 0]
...
[rosmaster.master][INFO] 2021-11-02 10:40:31,299: publisherUpdate[/evo/remote_key] -> http://localhost:19073/ ['http://localhost:19073/']
[rosmaster.master][INFO] 2021-11-02 10:40:31,300: publisherUpdate[/evo/remote_key] -> http://localhost:19073/ ['http://localhost:19073/']: sec=0.00, exception=<Fault -1: 'publisherUpdate: unknown method name'>
[rosmaster.threadpool][ERROR] 2021-11-02 10:40:31,300: Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
    result = cmd(*args)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
    ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
**Fault: <Fault -1: 'publisherUpdate: unknown method name'>**

I refer to many online answers, but it's useless！
So, has anyone encountered similar problems? Can you give me some suggestions？
Thanks a ton！！！

**Comment by xji-apex** [comment]
![image](https://user-images.githubusercontent.com/71243343/139783646-8c73c90e-cbbd-4de8-8183-f6cbe617eb3e.png)
![image](https://user-images.githubusercontent.com/71243343/139783730-416a5179-cd02-4611-99fd-d6af3bf63d1c.png)

**Comment by ghani35** [comment]
Hi, 
I am incoutring the same probme! if you solve the issue please let me know
