### ISSUE TITLE
Error while processing "dvs_tracking flyingroom"

### ISSUE THREAD

**Issue by thebox-ujt** [uzh-rpg/rpg_dvs_evo_open#4]
I tried to run the following steps in the order shown below, but I get an error and it stops halfway through.
Can I ask for an advice for their cause and a solution?

-Execution steps:
Terminal1: roslaunch dvs_tracking flyingroom.launch auto_trigger:=true
Terminal2: rosbag play -r 0.7 evo_flyingroom.bag

-Error messages:
================================================================================REQUIRED process [dvs_tracking-7] has died!
process has died [pid 4064, exit code -8, cmd /home/user/catkin_ws/devel/lib/dvs_tracking/dvs_tracking_ros events:=/dvs/events remote_key:=/evo/remote_key pointcloud:=dvs_mapping/pointcloud __name:=dvs_tracking __log:=/home/user/.ros/log/c87c824e-e92c-11eb-a2a5-080027ad98cd/dvs_tracking-7.log].
log file: /home/user/.ros/log/c87c824e-e92c-11eb-a2a5-080027ad98cd/dvs_tracking-7*.log
Initiating shutdown!
================================================================================
[rviz-13] killing on exit
[dvs_renderer_left-12] killing on exit
[rqt_evo-11] killing on exit
[snakify-10] killing on exit
[tf_to_camera_marker-9] killing on exit
[dvs_bootstrapping-8] killing on exit
[dvs_tracking-7] killing on exit
[trigger_map_expansion-6] killing on exit
[dvs_mapping-5] killing on exit
[pose_to_tf-4] killing on exit
[svo_gui-3] killing on exit
Unhandled exception in thread started by <bound method Thread.__bootstrap of <Thread(/tf, stopped daemon 139732130461440)>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 814, in __bootstrap_inner
    (self.name, _format_exc()))
  File "/usr/lib/python2.7/traceback.py", line 241, in format_exc
    etype, value, tb = sys.exc_info()
AttributeError: 'NoneType' object has no attribute 'exc_info'
[svo-2] killing on exit
*** Aborted at 1626766469 (unix time) try "date -d @1626766469" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x7fbc363a1410) received by PID 4062 (TID 0x7fbe5d9b9980) from PID 909775888; stack trace: ***
    @     0x7fbe5bc2d040 (unknown)
    @     0x7fbe5c5a516c _ZN18depth_from_defocus20DepthFromDefocusNode24projectEventsToVoxelGridERKSt6vectorIN5Eigen6MatrixIfLi4ELi1ELi0ELi4ELi1EEESaIS4_EERKS1_INS3_IfLi3ELi1ELi0ELi3ELi1EEESaIS9_EE._omp_fn.0
    @     0x7fbe537b7edf GOMP_parallel
    @     0x7fbe5c5a5304 depth_from_defocus::DepthFromDefocusNode::projectEventsToVoxelGrid()
    @     0x7fbe5c5a9fba depth_from_defocus::DepthFromDefocusNode::processEventQueue()
    @     0x7fbe5c5ae176 depth_from_defocus::DepthFromDefocusNode::update()
    @     0x7fbe5c5ae81a depth_from_defocus::DepthFromDefocusNode::remoteKeyCallback()
    @     0x7fbe5c5b94be boost::detail::function::void_function_obj_invoker1<>::invoke()
    @     0x7fbe5c5c470d ros::SubscriptionCallbackHelperT<>::call()
    @     0x7fbe5cb26152 ros::SubscriptionQueue::call()
    @     0x7fbe5cad0829 ros::CallbackQueue::callOneCB()
    @     0x7fbe5cad25cb ros::CallbackQueue::callAvailable()
    @     0x7fbe5cb29cf9 ros::SingleThreadedSpinner::spin()
    @     0x7fbe5cb1262b ros::spin()
    @     0x55f4e58377f4 rpg_common_main()
    @     0x55f4e5837306 main
    @     0x7fbe5bc0fbf7 __libc_start_main
    @     0x55f4e583749a _start
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by geothan** [comment]
Hi, i have similar issues. Have you managed to run the datasets?

i tried :
`roslaunch dvs_tracking flyingroom.launch auto_trigger:=true`
`rosbag play -r 0.7 /home/george/event_datasets/evo/evo_flyingroom.bag`

and rviz shows nothing

The output of first terminal returns multiple warnings:

[ WARN] [1641575533.511405484]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame world at time 1621507165,016965 according to authority unknown_publisher
Warning: TF_REPEATED_DATA ignoring data with redundant timestamp for frame world at time 1621507165.086958 according to authority default_authority
         at line 278 in /tmp/binarydeb/ros-noetic-tf2-0.7.5/src/buffer_core.cpp
Warning: TF_REPEATED_DATA ignoring data with redundant timestamp for frame world at time 1621507165.086958 according to authority default_authority
         at line 278 in /tmp/binarydeb/ros-noetic-tf2-0.7.5/src/buffer_core.cpp
[ WARN] [1641575533.595382290]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame world at time 1621507165,086958 according to authority unknown_publisher
